[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: www.google-analytics.com pbs.twimg.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' www.googletagmanager.com www.google-analytics.com; style-src 'self' 'unsafe-inline'; connect-src 'self' www.google-analytics.com pbs.twimg.com; font-src 'self' data:; media-src 'self' video.twimg.com;"
    Referrer-Policy = "strict-origin-when-cross-origin"
[build]
  command = "yarn build"
  publish = "public"
